<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PMB3RF0" failures="2" tests="28" name="ca.walmart.qa.testcases.LoginPageTestCases" time="486.932" errors="0" timestamp="2021-04-20T20:23:34 EDT" skipped="0">
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC5_FirstnameErrorMsg" time="9.724"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC17_InvalidEmail" time="10.953"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC13_Lessthan10Phone" time="13.615"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC18_PasswordMoreThan6" time="9.882"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC7_LastnameLessthan2Char" time="9.609"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC10_LastnameErrorMsg" time="10.097"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC1_FirstnameMoreThan2Char" time="50.147"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC4_BlankFirstnameMsg" time="9.886"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC9_BlankLastnameMsg" time="9.663"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC23_CharAndSpecialCharPassword" time="10.389"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC21_ShowPassword" time="12.853"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC6_LastnameMoreThan2Char" time="50.172"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC24_SpecialCharAndCharPassword" time="11.175"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC8_LastnameSpecialChar" time="9.582"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC11_blankPhone" time="49.844"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="loginPageTitleCheck" time="9.044"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC27_NumberPassword" time="9.766"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC2_FirstnameLessThan2Char" time="10.599"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC19_PasswordLessThan6" time="9.714"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC26_SpecialCharacterPassword" time="9.742">
    <failure message="expected [Password Strength: weak] but found [Password Strength: moderate]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Password Strength: weak] but found [Password Strength: moderate]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ca.walmart.qa.testcases.LoginPageTestCases.Login_TC26_SpecialCharacterPassword(LoginPageTestCases.java:284)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Login_TC26_SpecialCharacterPassword -->
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC14_Morethan10Phone" time="10.490"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC25_CharacterPassword" time="9.323"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC20_EncryptPassword" time="9.167"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC12_Exact10Phone" time="49.757"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC16_ValidEmail" time="49.809"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC22_StrongPassword" time="10.748"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC3_FirstnameSpecialChar" time="10.532"/>
  <system-out/>
  <testcase classname="ca.walmart.qa.testcases.LoginPageTestCases" name="Login_TC15_ErrorMessagePhone" time="10.650">
    <failure message="expected [Please enter valid phone number.] but found [Please enter a valid phone number.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Please enter valid phone number.] but found [Please enter a valid phone number.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ca.walmart.qa.testcases.LoginPageTestCases.Login_TC15_ErrorMessagePhone(LoginPageTestCases.java:183)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Login_TC15_ErrorMessagePhone -->
  <system-out/>
</testsuite> <!-- ca.walmart.qa.testcases.LoginPageTestCases -->
